Ready
Strandol/markup-task-1 pull request #1
Opened 2017-01-08 00:41 UTC by Strandol

2017-01-08 00:41 UTC, Strandol commented
@DudaGod come to watching

2017-01-09 18:18 UTC, DudaGod commented on package.json
>    },
ты тут husky не поставил, модуль про который с тобой разговаривали и который позволяет делать такой `precommit` хук как у тебя в `scripts` указан

2017-01-09 19:50 UTC, DudaGod requested changes

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +    <meta name="keywords" content="Yandex, YandexMail, LoadSpeed">
тогда бы и `description` указал что-ли

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +    <meta name="keywords" content="Yandex, YandexMail, LoadSpeed">
Давай тут еще Open Graph-а немного юзнем. Вот тут про него рассказывалось - https://rawgit.com/urfu-2016/markup-slides/master/01-html/index.html#/41
и тут - https://github.com/urfu-2015/verstka-lectures/blob/master/html/part-1.md#meta-

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +    <title>Блог компании Яндекс</title>
Это должно быть не только в теге title. Так как это основной текст.
Давай его добавим еще в header например и выделим в h1

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +    <main>
давай для этого тега укажем правильную роль - http://gaserge.ru/blog/html,css/atribut-role-v-html5.html (тут правда с матюками, зато инфа правильная)

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +            и новая логика. Всё это напрямую влияет на скорость работы интерфейса.</p><br>
У тебя тут много текста в теге <p>. Следовательно по гайду - https://github.com/urfu-2016/guides/blob/master/codestyle/html.md
мы пишем его так:
```html
<p>
    text
</p>
```

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +            и новая логика. Всё это напрямую влияет на скорость работы интерфейса.</p><br>
И зачем тебе `<br>` в конце? Ведь `p` - блочный тег и он сам вставляет отступ.

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <h3>Этапы первой загрузки</h3>
кажется это не нужно выносить в `h3` достаточно вынести в тег `p`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                    <li>загрузка статики (HTTP-запрос и парсинг);</li>
давай HTTP унесем в тег `abbr` и укажем правильный атрибут `title` в котором опишем что эта аббревиатура значит

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                    <li>обновление DOM.</li>
DOM - тоже давай в `abbr`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
судя по гайду пробельных символов быть не должно

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                — «А что будем считать?» - уточняете вы</p><br>
здесь тоже все что внутри тега p - внутрь (как и выше). И в конце тег `br` не нужен

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>— «Ок, теперь у нас есть метрики, мы можем отправить их на сервер» - говорим мы<br>
Вот тут, везде где у тебя кавычки, давай по ставим тег `q`. Почитай кстати про него.

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
пустая строка

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>Как вы знаете, <dfn>медиана</dfn> – это серединное, а не среднее значение в выборке.
за тег `dfn` - 👍

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                В общем случае медиана отлично показывает, сколько грузится средний пользователь.</p><br>
та же проблема, `p` и `br`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
лишняя пустая строка

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                рассказать, сколько пользователей ускорилось, а сколько замедлилось.</p><br>
`p` и `br`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
пустая строка

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p><dfn>APDEX</dfn> – метрика, которая сразу говорит: хорошо или плохо. Метрика
с `dfn` молодец, но в данном случае это же не только определение, но и аббревеатура.
Давай внутрь `dfn` положим `abbr` с правильным тайтлом

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                но уже не настолько счастлив. И применяем формулу:</p><br>
`p` и `br`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                работает очень просто. Мы выбираем временной интервал [0; t], такой, что если
давай `[0; t]` давай уберем в тег `code` - прочитай кстати про него еще раз

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                интервал, (t; 4t] (в четыре раза больше первого), и считаем, что если страница
и тут - `(t; 4t]` давай `code` юзнем

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
пустая строка

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                хорошо или плохо работает почта.</p>
а здесь почему то решил `br` уже не ставить? )
Текст внутрь `p` унеси

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p><span>(кол-во счастливых пользователей + кол-во удовлетворенных / 2) / (кол-во всех).</span>
а почему ты тут эту формулу запихал в `span`?
Давай `кол-во счастливых пользователей` и остальные предполагаемые переменные запишем в `var`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
вот здесь между `section` я на самом деле тоже люблю пустые строки оставлять. Так легче читается потом. Так что давай оставим. То есть будем их оставлять между крупными блоками

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                мы уже делаем следующее:</p>
p

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +
пустая строка. И везде ниже тоже пустые строки поисправляй

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>Мы подумали: «А что если хранить где-то старую версию файлов, а при выходе новой
давай прямую речь в `q`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                В браузере же останется просто наложить патч на клиенте.</p><br>
`p` и `br`. В общем и везде ниже это тоже исправь.

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>На самое деле эта идея не нова. Уже существуют стандарты для HTTP — например,
на самом*

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                </pre><br>
это таблица должна быть =)

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                </pre><br>
вот тут `pre` и все что внутри должно к правом краю лепится. То есть вообще без отступов. Только внутри `pre` отступы должны быть

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                ресурса. <span>p</span> — патч для ресурса, который сгенерировал vcdiff. <span>s</span> — чексумма для
тут везде вместо `span` правильнее использовать будет `var`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <div>
почему `div` а не `p`?

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                    <p>дано &#949, &#967<sub>0</sub><br>
а всю внутренность давай в `code` запишем вместо `p`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                наложения патча на клиенте. Чексумма вычисляется по алгоритму Флетчера.</p>
у тебя код алгоритма по идеи после этого блока должен быть

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                </dl>
молоток за dl, dt, dd - :1st_place_medal:

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                    <dt>CRC16/32</dt><dd>- алгоритм нахождения контрольной суммы, предназначенный для проверки
давай только `dd` ставить на следующую строку, так читать приятнее

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                </pre>
это должна быть таблица

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +            </section>
это больше на тег `address` похоже, чем на `section`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>Компания: Яндекс</p>
и зачем ты каждую из строк уносишь в тег `p`? Используй просто `br` внутри `address`. И кстати не обязательно всегда начинать писать с новой строки если юзнул тег `br`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <p>Электронная почта: (doochik@yandex-team.ru)</p>
как ты думаешь в какой тег было бы круто унести эту ссылку на мыло?

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <h4>- Mogaika (mogaika@yandex-team.ru) 30 ноября 2014 в 17:0</h4>
это больше на `address` похоже и ноль в конце потерял

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                <h4>- Mogaika (mogaika@yandex-team.ru) 30 ноября 2014 в 17:0</h4>
А дату со временем можно в спец. тег `time` запусать

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +        <address>© Яндекс, help@yandex.ru, Хохрякова, 10</address>
© - вместо этого должен быть тег

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +                хорошо или плохо работает почта.</q>
это скорее `blockquote`, а не `q`

2017-01-09 19:50 UTC, DudaGod commented on index.html
> +    <footer>
давай футеру роль укажем

2017-01-09 21:59 UTC, Strandol commented on index.html
> +                <p>Как вы знаете, <dfn>медиана</dfn> – это серединное, а не среднее значение в выборке.
@DudaGod :)

2017-01-09 22:03 UTC, Strandol commented on index.html
> +                интервал, (t; 4t] (в четыре раза больше первого), и считаем, что если страница
@DudaGod Почитал, просто забыл что может юзаться еще для подобных выражений, думал чисто код)
не обратил внимание

2017-01-20 21:39 UTC, DudaGod commented on index.html
> +    <meta property="og:image" content="src\img\cat.jpg">
слеши то в другую сторону ставятся )

2017-01-20 21:39 UTC, DudaGod commented on index.html
> +    </style>
кстати ты это мог бы еще атрибутами для table указать вместо стилей, не критично

2017-01-20 21:40 UTC, DudaGod commented on index.html
> +                    <li>загрузка статики (<abbr title=" HyperText Transfer Protocol">HTTP</abbr>-запрос и парсинг);</li>
тут кажется li длинее 80 символов, нужно перевести строку и контент положить в середину

2017-01-20 21:41 UTC, DudaGod commented on index.html
> +                    — <q>«Ок, теперь у нас есть метрики, мы можем отправить их на сервер»</q> - говорим мы<br>
разве тег <q> сам не добавляет кавычки? Которые ты тут руками написал?

2017-01-20 21:41 UTC, DudaGod commented on index.html
> +                    <dfn><abbr title="Application Performance Index">APDEX</abbr></dfn> – метрика, которая сразу говорит: хорошо или плохо. Метрика
эта строка длинная

2017-01-20 21:42 UTC, DudaGod commented on index.html
> +                    (<var>кол-во счастливых пользователей</var> + <var>кол-во удовлетворенных</var> / 2) / (<var>кол-во всех</var>).
и эта длинная получилась перенеси на вторую сразу после символа деления

2017-01-20 21:42 UTC, DudaGod commented on index.html
> +                </pre><br>
где таблица то? )

2017-01-20 21:43 UTC, DudaGod commented
в остальном ок

2017-01-21 12:27 UTC, Strandol commented on index.html
> +                    — <q>«Ок, теперь у нас есть метрики, мы можем отправить их на сервер»</q> - говорим мы<br>
@DudaGod Не, в атоме не пишет

2017-01-21 12:32 UTC, merged

2026-09-02 04:38 UTC, prashanthreddys commented on index.html
> +                </pre>
Fixed in 4b2f153b8. Extracted the composition-root wiring into an exported assertStationBootGuard(authMode, nodeEnv, station) in index.ts that reads STATION and calls resolveDeploymentEnv itself; main() now calls it, and the test drives the STATION table through assertStationBootGuard (not a duplicated wrapper), so the real STATION->ring->throw chain at the composition root is what the test now exercises. Also added two divergent cases calling the guard directly with a deploymentEnv that disagrees with STATION (ring=local-dev/STATION=prod throws; ring=prod/STATION=local-dev no-ops) to pin that the ring parameter, not STATION, drives the throw.